// GENERATED by tools/keygen — DO NOT EDIT BY HAND.
const List<int> nusaActivationPublicKey = <int>[122, 215, 191, 114, 69, 180, 152, 110, 241, 248, 114, 90, 155, 200, 193, 68, 152, 169, 36, 12, 32, 127, 176, 50, 174, 76, 13, 39, 254, 67, 164, 95];
