// GENERATED by tools/keygen — DO NOT EDIT BY HAND.
const List<int> nusaActivationPublicKey = <int>[113, 43, 40, 113, 85, 141, 83, 191, 8, 190, 73, 60, 123, 211, 37, 71, 6, 119, 21, 36, 244, 246, 94, 155, 38, 67, 145, 79, 194, 1, 149, 25];
