-- NUSA KASIR -- Online Store migration
-- Add slug to store_settings + ensure online_orders table exists
ALTER TABLE IF EXISTS store_settings ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
UPDATE store_settings SET slug = LOWER(REGEXP_REPLACE(store_name, '[^a-zA-Z0-9]+', '-', 'g')) WHERE slug IS NULL;

-- Ensure online_orders has proper constraints
CREATE TABLE IF NOT EXISTS online_orders (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id      TEXT NOT NULL,
  invoice       TEXT NOT NULL,
  customer_name TEXT NOT NULL DEFAULT '',
  customer_phone TEXT NOT NULL DEFAULT '',
  items         JSONB DEFAULT '[]'::jsonb,
  subtotal      INTEGER DEFAULT 0,
  discount      INTEGER DEFAULT 0,
  promo_code    TEXT DEFAULT '',
  handling_fee  INTEGER DEFAULT 0,
  total         INTEGER DEFAULT 0,
  payment_method TEXT DEFAULT 'Tunai',
  pickup_time   TEXT DEFAULT 'Segera',
  branch        TEXT DEFAULT 'Pusat',
  notes         TEXT DEFAULT '',
  status        TEXT DEFAULT 'Online Baru',
  processed_by  TEXT DEFAULT '',
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_store_settings_slug ON store_settings(slug);
CREATE INDEX IF NOT EXISTS idx_online_orders_store ON online_orders(store_id);
CREATE INDEX IF NOT EXISTS idx_online_orders_phone ON online_orders(customer_phone);
CREATE INDEX IF NOT EXISTS idx_online_orders_status ON online_orders(status);

-- Allow public reads on active stores
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read active stores" ON store_settings;
CREATE POLICY "Public can read active stores" ON store_settings FOR SELECT USING (is_active = TRUE);

ALTER TABLE online_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read published products" ON online_products;
CREATE POLICY "Public can read published products" ON online_products FOR SELECT USING (is_published = TRUE);

ALTER TABLE online_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can insert orders" ON online_orders;
CREATE POLICY "Public can insert orders" ON online_orders FOR INSERT WITH CHECK (TRUE);
DROP POLICY IF EXISTS "Public can read own orders" ON online_orders;
CREATE POLICY "Public can read own orders" ON online_orders FOR SELECT USING (TRUE);
